### ISSUE TITLE
add KWVerificationCodeView Programatically

### ISSUE THREAD

**Issue by d33pak-s1ngh** [keepworks/KWVerificationCodeView#10]
I want to add verification view  programatically to my controller following code i have used. but it is not working properly because i dont know what properties need to be set programatically. Also can you update this to latest ios versions.

```swift
let secondView: KWVerificationCodeView = {
        let vv = KWVerificationCodeView()
        vv.digits = 6
        vv.underlineColor = UIColor.darkGray
        vv.backgroundColor = UIColor.clear
        vv.textSize = 24
        //vv.textFont =
        vv.tintColor = UIColor.blue
        //vv.darkKeyboard =
        vv.translatesAutoresizingMaskIntoConstraints = false
        return vv
    }()

func setupVerificationView(){
        self.view.addSubview(secondView)
        secondView.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
        secondView.trailingAnchor.constraint(equalTo: view.trailingAnchor).isActive = true
        secondView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor,constant: 50).isActive = true
        secondView.heightAnchor.constraint(equalToConstant: 80).isActive = true
}

**Comment by kpavankotesh** [comment]
@d33pak-s1ngh There aren't any mandatory properties you need to set to use KWVerificationCodeView. If not set, it takes the default values. Just make sure you set your constraints properly. It should work fine.

**Comment by d33pak-s1ngh** [comment]
Well i have tried to add KWVerificationCodeView programatically but it is not working as expected check this image [https://ibb.co/fr3gjd](url)
Following is my code.
`import UIKit
import KWVerificationCodeView

class Test: UIViewController{
    
    let verificationView : KWVerificationCodeView = {
        let vv = KWVerificationCodeView()
        vv.digits = 6
        vv.translatesAutoresizingMaskIntoConstraints = false
        return vv
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        
        view.addSubview(verificationView)
        
        verificationView.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
        verificationView.centerYAnchor.constraint(equalTo: view.centerYAnchor).isActive = true
        verificationView.leadingAnchor.constraint(equalTo: view.leadingAnchor,constant: 8).isActive = true
        verificationView.trailingAnchor.constraint(equalTo: view.trailingAnchor).isActive = true
    }
}
`

can you please tell me what is wrong with above code. Or you can provide a sample code for adding KWVerificationView Programatically.
That will be very helpful.
Thank You.

**Comment by kpavankotesh** [comment]
@d33pak-s1ngh I made the init method `public` to be able to programatically add KWVerificationCodeView. Please update your pod to latest version `0.1.6` I just published.

Also I've added a basic example on how to use the view programatically. You can refer the [example](https://github.com/keepworks/KWVerificationCodeView/blob/master/Example/KWVerificationCodeView/ProgramaticalVerificationCodeViewController.swift) for the same.

**Comment by d33pak-s1ngh** [comment]
i am not getting version  0.1.6 when i do pod install `pod 'KWVerificationCodeView'` i am  still getting 0.1.5
so then i tried to add `'KWVerificationCodeView', '~> 0.1.6'` in my pod file which gives error.

**Comment by d33pak-s1ngh** [comment]
got the 0.1.6 thank you @kpavankotesh .

**Comment by d33pak-s1ngh** [comment]
@kpavankotesh  One issue is that it is not working with auto layout constraints.
